### ISSUE TITLE
Segmentation fault everytime press keybind.

### ISSUE THREAD

**Issue by lidgnulinux** [Z572/gwwm#3]
## Info
dwl's commit: master.
wlroots version: 0.15.1.
## Description
I managed to compile gwwm and launch it on my debian machine, but gwwm suddenly kick me to TTY everytime I press keybind (e.g. super+p). It's always started by a hang condition then straight to TTY after that. Any clue ? Thanks.
This is my init.scm : 

```
(use-modules (gwwm)
             (gwwm config)
             (gwwm commands)
             (gwwm keymap)
             (gwwm hooks)
             (gwwm color))
;;; win+d
(keymap-global-set (kbd (s p)) (lambda () (spawn "sakura")))
(gwwm
 (borderpx 1)
 (sloppyfocus? #t)
 (xkb-rules
  (make-xkb-rules
   "us"
   #:model "asus_laptop"
   #:options
   '("ctrl:ralt_rctrl"
     "ctrl:swapcaps_hyper"
     "shift:both_capslock")))
 (bordercolor (make-color 1.0 1.0 1.0 0.1)))
```

**Comment by Z572** [comment]
Sorry I can't reproduce, can you reproduce with the latest commit?  and tell me what commit are you use.

**Comment by Z572** [comment]
sorry, i forgot to commit some changes to guile-wlroots,can you use latest commit for guile-wlroots,gwwm and try again?

**Comment by lidgnulinux** [comment]
I will try it again, thanks.

**Comment by lidgnulinux** [comment]
So, I recompile guile-wlroots, guile-wayland, and gwwm and it still kicks me to tty everytime I press keybind.

**Comment by Z572** [comment]
please test again, before gwwm commit 86d3d77b4c5d625fcca77c4536a7facf0f94b66e, X11 app will make gwwm Segmentation fault.

**Comment by Z572** [comment]
I do not use X11 app, so some bug about xwayland i can't found, such as setfullscreen not work for X11 app

**Comment by Z572** [comment]
maybe you can try let sakura use wayland backend

**Comment by lidgnulinux** [comment]
Hello, I'm trying gwwm on Ubuntu and again I get kicked to TTY when I press keybind to launch foot (wayland terminal). I try both from TTY and from other wayland compositor, I get same result.

**Comment by lidgnulinux** [comment]
I change foot with havoc terminal and it could be launched, I'm trying to use wofi launcher and yambar bar but they don't show. It's really strange to see wayland native tools don't work on a wayland compositor.

**Comment by Z572** [comment]
Is a bug, please pull and try agenda. I am use SCHEME replace C, break something is normal, if you found one, please open new issues.
