### ISSUE TITLE
Unbound variable: main

### ISSUE THREAD

**Issue by wehlutyk** [Z572/gwwm#7]
## Info
gwwm's commit: 1fb0c6685570260174eaa45a5646634790d99423
guile-wlroots's commit: Z572/guile-wlroots@79137bd859814bf5f41db8d006212a792ec791a3
guile-wayland's commit: Z572/guile-wayland@659919ecd4426a760c4ecce3df10e9b3ae72f130
guile version: 3.0.9
wlroots version: 0.17.4
OS: Guix
```bash
Generation 65	Nov 05 2024 06:47:09	(current)
  nonguix 9f065c3
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: 9f065c321e7d6b39f8610a8d65528f79a8733459
  guix-science 7304e37
    repository URL: https://codeberg.org/guix-science/guix-science.git
    branch: master
    commit: 7304e37d4d664f27a18577e388c91413878d62fc
  guix 33665c5
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: 33665c52c4670bc3b4d337c89ac9cc6c4c69b26f
```
log file: (below)

## Description

After following Readme's [develop](https://github.com/Z572/gwwm?tab=readme-ov-file#develop):
```
$ bin/gwwm
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling .../bin/gwwm
;;; compiling .../gwwm.scm
;;; compiling .../gwwm/client.scm
;;; WARNING: compilation of .../gwwm/client.scm failed:
;;; In procedure dlopen: file "libgwwm.so", message "libgwwm.so: cannot open shared object file: No such file or directory"
;;; WARNING: compilation of .../gwwm.scm failed:
;;; In procedure dlopen: file "libgwwm.so", message "libgwwm.so: cannot open shared object file: No such file or directory"
;;; WARNING: compilation of .../bin/gwwm failed:
;;; In procedure dlopen: file "libgwwm.so", message "libgwwm.so: cannot open shared object file: No such file or directory"
Backtrace:
           3 (primitive-load ".../bin/gwwm")
In ice-9/eval.scm:
   196:35  2 (_ #f)
   223:20  1 (proc #<directory (guile-user) 7f2715d17c80>)
In unknown file:
           0 (%resolve-variable (7 . main) #<directory (guile-user) …>)

ERROR: In procedure %resolve-variable:
Unbound variable: main
```

As a sidenote (which may be the problem), by default I run into #6, and adding `(add-to-load-path (dirname (dirname (current-filename))))` to `bin/gwwm.in` worked, bringing me to the bug above.

So `bin/gwwm.in` became
```
#!@GUILE@
!#
(add-to-load-path (dirname (dirname (current-filename))))
(use-modules (gwwm))

(bindtextdomain "gwwm" "@localedir@")
(apply main (command-line))
;;; Local Variables:
;;; mode: scheme
;;; End:
```

**Comment by wehlutyk** [comment]
Fixed given a full list of the `gwwm`/`guile-*` packages together [.guix/modules/gwwm-packages.scm](https://gitlab.com/wehlutyk/edl/-/blob/main/.guix/modules/gwwm-packages.scm), and returning `gwwm` at the bottom (again following Guix's Cookbook [The Repository as a Channel](https://guix.gnu.org/cookbook/en/html_node/The-Repository-as-a-Channel.html)).

`guix shell -L .guix/modules [-D] -f .guix/modules/gwwm-packages.scm` then works. With `-D` it gives indeed the dev environment.

Without `-D`, and with #8, it makes the working `gwwm` command.

**Comment by Z572** [comment]
you can use `./pre-inst-env bin/gwwm` , pre-inst-env will set requires environments

or just `make run`.

**Comment by wehlutyk** [comment]
From inside the guix shell update in [develop](https://github.com/Z572/gwwm?tab=readme-ov-file#develop) worked for me. Thanks for the fixes!
